version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: carteira
    ports:
    - 3306:3306
    volumes:
    - carteira_data:/var/lib/mysql

volumes:
  carteira_data:
